packages:
  - .
  - docs

ignoredBuiltDependencies:
  - core-js-pure
  - spawn-sync
  - svelte-preprocess

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@moonrepo/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - oxc-resolver
  - sharp
