/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchEnginesImport } from './routes/search-engines'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SearchEnginesRoute = SearchEnginesImport.update({
  id: '/search-engines',
  path: '/search-engines',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/search-engines': {
      id: '/search-engines'
      path: '/search-engines'
      fullPath: '/search-engines'
      preLoaderRoute: typeof SearchEnginesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search-engines': typeof SearchEnginesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search-engines': typeof SearchEnginesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/search-engines': typeof SearchEnginesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search-engines'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search-engines'
  id: '__root__' | '/' | '/search-engines'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchEnginesRoute: typeof SearchEnginesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchEnginesRoute: SearchEnginesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search-engines"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/search-engines": {
      "filePath": "search-engines.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
